spring:
  profiles: docker
  datasource:
    url : ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      static-locations: ${STATIC_LOCATIONS}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html


solutions:
  base-path: ${SOLUTIONS_BASE_PATH}

fastapi:
  base-url: ${FASTAPI_BASE_URL}