spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/algomate_db
    username: algomate
    password: algomate7897
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      static-locations: file:/Users/sungho/Documents/study/Algomate/algorithm-mate/src/main/resources/solutions/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

fastapi:
  base-url: "http://13.239.190.188"  # FastAPI 서버 URL


