spring:
  datasource:
    url : jdbc:postgresql://algomate-db.crwmy48cc6rr.ap-southeast-2.rds.amazonaws.com:5432/algomate_db
    username: algomate
    password: algomate7897
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  web:
    resources:
      static-locations: file:/app/resources/solutions/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

fastapi:
  base-url: "http://13.239.190.188"