name: Build Docker Images

on:
  push:
    branches: [main, feat/#21]
    paths:
      - 'crawling/**'
      - 'algorithm-mate/**'
      - 'algomate-nginx/**'
  workflow_dispatch:  # 수동 트리거 가능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Crawling Image (Public)
        working-directory: ./crawling
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/crawling:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/crawling:latest .
      - name: Build Spring Boot Image (Private)
        working-directory: ./algorithm-mate
        run: |
          ./gradlew build -Pspring.profiles.active=docker -x test
          docker build -t ${{ secrets.DOCKER_USERNAME }}/algomate:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/algomate:latest .
      - name: Build Nginx Image (Public)
        working-directory: ./algomate-nginx
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/nginx:latest .