name: CI/CD for Algomate

on:
  push:
    branches: [main, feat/#21]  # feat/#21 브랜치도 포함
    paths:
      - 'crawling/**'
      - 'algorithm-mate/**'
      - 'algomate-nginx/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Crawling Image (Public)
        working-directory: ./crawling
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/crawling:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/crawling:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/crawling:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/crawling:latest
      - name: Build and Push Spring Boot Image (Private)
        working-directory: ./algorithm-mate
        run: |
          ./gradlew build -Pspring.profiles.active=docker -x test
          docker build -t ${{ secrets.DOCKER_USERNAME }}/algomate:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/algomate:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/algomate:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/algomate:latest
      - name: Build and Push Nginx Image (Public)
        working-directory: ./algomate-nginx
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/nginx:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/algomate
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            docker-compose down
            sed -i "s|image: .*fastapi_app$|image: ${{ secrets.DOCKER_USERNAME }}/crawling:${{ github.sha }}|g" docker-compose.yml
            sed -i "s|image: .*celery_worker$|image: ${{ secrets.DOCKER_USERNAME }}/crawling:${{ github.sha }}|g" docker-compose.yml
            sed -i "s|image: .*spring-boot$|image: ${{ secrets.DOCKER_USERNAME }}/algomate:${{ github.sha }}|g" docker-compose.yml  # Private 저장소 사용
            sed -i "s|image: .*nginx$|image: ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }}|g" docker-compose.yml
            docker-compose pull
            docker-compose up -d --remove-orphans
            docker-compose ps
            docker logs fastapi_app
            docker logs celery_worker
            docker logs spring-boot
            docker logs nginx