name: Push Docker Images

on:
  push:
    branches: [main, feat/#21]
    paths:
      - 'crawling/**'
      - 'algorithm-mate/**'
      - 'algomate-nginx/**'
  workflow_dispatch:  # 수동 트리거 가능
  needs: build  # build 작업 완료 후 실행

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Crawling Image (Public)
        working-directory: ./crawling
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/crawling:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/crawling:latest
      - name: Push Spring Boot Image (Private)
        working-directory: ./algorithm-mate
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/algomate:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/algomate:latest
      - name: Push Nginx Image (Public)
        working-directory: ./algomate-nginx
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest